#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot the 4-CC comparison generated by run_4cc_comparison.py.

Input directory layout:
  experiment_root/
    BBRv2/
    oBBR/
    BBRv2plus/
    F-BBR/
    compare/
"""

import argparse
import csv
import math
import re
from bisect import bisect_right
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


DEFAULT_CCS = ("BBRv2", "oBBR", "BBRv2plus", "F-BBR")
PLOT_COLORS = {
    "BBRv2": "#1f77b4",
    "FreqCCv4": "#ff7f0e",
    "oBBR": "#2ca02c",
    "BBRv2plus": "#d62728",
    "F-BBR": "#9467bd",
}


def split_csv(text: str) -> List[str]:
    return [part.strip() for part in str(text).split(",") if part.strip()]


def parse_rate_bps(text: str) -> float:
    value = str(text).strip()
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)\s*([kKmMgG]?)\s*(?:b(?:it)?s?|bps)?", value)
    if not match:
        raise ValueError(f"无法解析速率: {text}")
    number = float(match.group(1))
    unit = match.group(2).lower()
    scale = {"": 1.0, "k": 1e3, "m": 1e6, "g": 1e9}[unit]
    return number * scale


def read_two_column_trace(path: Path) -> List[Tuple[float, float]]:
    rows: List[Tuple[float, float]] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) < 2:
                continue
            try:
                rows.append((float(fields[0]), float(fields[1])))
            except ValueError:
                continue
    rows.sort(key=lambda item: item[0])
    return rows


def read_queue_trace(path: Path, service_rate_bps: float) -> List[Tuple[float, float]]:
    rows: List[Tuple[float, float]] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) < 2:
                continue
            try:
                time_s = float(fields[0])
                queue_bytes = float(fields[1])
            except ValueError:
                continue
            delay_ms = queue_bytes * 8.0 / service_rate_bps * 1000.0
            rows.append((time_s, delay_ms))
    rows.sort(key=lambda item: item[0])
    return rows


def sample_previous(series: Sequence[Tuple[float, float]], grid: Sequence[float]) -> List[float]:
    if not series:
        return [math.nan for _ in grid]
    times = [item[0] for item in series]
    values = [item[1] for item in series]
    sampled: List[float] = []
    for t in grid:
        idx = bisect_right(times, t) - 1
        if idx < 0:
            sampled.append(0.0)
        else:
            sampled.append(values[idx])
    return sampled


def mean_ignore_nan(values: Iterable[float]) -> float:
    valid = [value for value in values if not math.isnan(value)]
    if not valid:
        return math.nan
    return sum(valid) / len(valid)


def percentile(values: Iterable[float], pct: float) -> float:
    valid = sorted(value for value in values if not math.isnan(value))
    if not valid:
        return math.nan
    if len(valid) == 1:
        return valid[0]
    pos = (len(valid) - 1) * pct / 100.0
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return valid[lo]
    return valid[lo] + (valid[hi] - valid[lo]) * (pos - lo)


def build_time_grid(max_time_s: float, step_s: float) -> List[float]:
    if max_time_s <= 0:
        return [0.0]
    count = int(math.ceil(max_time_s / step_s)) + 1
    return [round(i * step_s, 10) for i in range(count)]


def find_goodput_files(run_dir: Path, trace_name: str, cc: str) -> List[Path]:
    exact = sorted(run_dir.glob(f"{trace_name}_flow*_{cc}_good.txt"))
    if exact:
        return exact
    return sorted(run_dir.glob("*_flow*_*_good.txt"))


def find_queue_files(run_dir: Path, trace_name: str) -> List[Path]:
    shared = sorted(run_dir.glob(f"{trace_name}_shared_bottleneck_queue.txt"))
    if shared:
        return shared
    exact = sorted(run_dir.glob(f"{trace_name}_switch_egress_flow*_bottleneck_queue.txt"))
    if exact:
        return exact
    shared_fallback = sorted(run_dir.glob("*_shared_bottleneck_queue.txt"))
    if shared_fallback:
        return shared_fallback
    return sorted(run_dir.glob("*_switch_egress_flow*_bottleneck_queue.txt"))


def load_cc_data(
    experiment_dir: Path,
    cc: str,
    trace_name: str,
    service_rate_bps: float,
) -> Dict[str, object]:
    run_dir = experiment_dir / cc
    goodput_files = find_goodput_files(run_dir, trace_name, cc)
    queue_files = find_queue_files(run_dir, trace_name)

    goodput = [read_two_column_trace(path) for path in goodput_files]
    queue_delay = [read_queue_trace(path, service_rate_bps) for path in queue_files]
    max_time = 0.0
    for series in goodput + queue_delay:
        if series:
            max_time = max(max_time, series[-1][0])
    return {
        "run_dir": run_dir,
        "goodput_files": goodput_files,
        "queue_files": queue_files,
        "goodput": goodput,
        "queue_delay": queue_delay,
        "max_time": max_time,
    }


def write_timeseries_csv(path: Path, grid: Sequence[float], values_by_cc: Dict[str, Sequence[float]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["time_s", *values_by_cc.keys()])
        for idx, time_s in enumerate(grid):
            row = [time_s]
            for values in values_by_cc.values():
                value = values[idx]
                row.append("" if math.isnan(value) else f"{value:.6f}")
            writer.writerow(row)


def plot_lines(
    output: Path,
    grid: Sequence[float],
    values_by_cc: Dict[str, Sequence[float]],
    ylabel: str,
    title: str,
    ideal_line: Optional[float] = None,
) -> None:
    fig, ax = plt.subplots(figsize=(10.5, 5.6))
    for cc, values in values_by_cc.items():
        ax.plot(grid, values, label=cc, linewidth=1.8, color=PLOT_COLORS.get(cc))
    if ideal_line is not None:
        ax.axhline(ideal_line, color="#555555", linestyle="--", linewidth=1.0, label="ideal capacity")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=2, frameon=False)
    fig.tight_layout()
    fig.savefig(output, dpi=180)
    plt.close(fig)


def plot_bar(output: Path, values: Dict[str, float], ylabel: str, title: str) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 4.8))
    ccs = list(values.keys())
    heights = [values[cc] for cc in ccs]
    ax.bar(ccs, heights, color=[PLOT_COLORS.get(cc, "#777777") for cc in ccs])
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(output, dpi=180)
    plt.close(fig)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="汇总四个 CC 子实验的 goodput/队列 trace，并在 compare 目录画对比图。",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("--experiment-dir", required=True, help="复合实验根目录，里面应包含 BBRv2/oBBR/BBRv2plus/F-BBR 子目录。")
    parser.add_argument("--service-rate", default="100Mbps", help="共享瓶颈链路速率，用于把队列字节换算成排队延迟。")
    parser.add_argument("--n-flows", type=int, default=4, help="每个子实验的流数量。默认 4。")
    parser.add_argument("--ccs", default=",".join(DEFAULT_CCS), help="要比较的 CC 子目录名，逗号分隔。")
    parser.add_argument("--trace-names", default="", help="每个 CC 对应的 traceName，默认与 CC 名相同。")
    parser.add_argument("--sample-step-s", type=float, default=0.1, help="绘图重采样时间步长。默认 0.1s。")
    parser.add_argument("--warmup-s", type=float, default=5.0, help="汇总平均值时跳过的启动阶段。默认 5s。")
    args = parser.parse_args(argv)

    experiment_dir = Path(args.experiment_dir).expanduser().resolve()
    compare_dir = experiment_dir / "compare"
    compare_dir.mkdir(parents=True, exist_ok=True)

    ccs = split_csv(args.ccs)
    trace_names = split_csv(args.trace_names) if args.trace_names else list(ccs)
    if len(trace_names) != len(ccs):
        raise SystemExit("trace-names 必须为空，或与 ccs 数量相同。")
    trace_name_by_cc = dict(zip(ccs, trace_names))
    service_rate_bps = parse_rate_bps(args.service_rate)

    raw = {
        cc: load_cc_data(experiment_dir, cc, trace_name_by_cc[cc], service_rate_bps)
        for cc in ccs
    }
    max_time = max(float(item["max_time"]) for item in raw.values())
    grid = build_time_grid(max_time, args.sample_step_s)

    aggregate_tput: Dict[str, List[float]] = {}
    mean_tput: Dict[str, List[float]] = {}
    mean_qdelay: Dict[str, List[float]] = {}
    p95_qdelay: Dict[str, float] = {}
    avg_qdelay: Dict[str, float] = {}
    avg_aggregate_tput: Dict[str, float] = {}

    for cc in ccs:
        goodput_series = raw[cc]["goodput"]  # type: ignore[index]
        queue_series = raw[cc]["queue_delay"]  # type: ignore[index]
        sampled_goodput = [sample_previous(series, grid) for series in goodput_series]  # type: ignore[arg-type]
        sampled_queue = [sample_previous(series, grid) for series in queue_series]  # type: ignore[arg-type]

        aggregate: List[float] = []
        per_flow_mean: List[float] = []
        for idx in range(len(grid)):
            values_kbps = [series[idx] for series in sampled_goodput]
            total_mbps = sum(v for v in values_kbps if not math.isnan(v)) / 1000.0
            aggregate.append(total_mbps)
            per_flow_mean.append(mean_ignore_nan(values_kbps) / 1000.0)
        aggregate_tput[cc] = aggregate
        mean_tput[cc] = per_flow_mean

        q_mean: List[float] = []
        for idx in range(len(grid)):
            q_mean.append(mean_ignore_nan(series[idx] for series in sampled_queue))
        mean_qdelay[cc] = q_mean

        steady_indexes = [idx for idx, time_s in enumerate(grid) if time_s >= args.warmup_s]
        if not steady_indexes:
            steady_indexes = list(range(len(grid)))
        steady_tput = [aggregate[idx] for idx in steady_indexes]
        steady_q = [q_mean[idx] for idx in steady_indexes]
        avg_aggregate_tput[cc] = mean_ignore_nan(steady_tput)
        avg_qdelay[cc] = mean_ignore_nan(steady_q)
        p95_qdelay[cc] = percentile(steady_q, 95.0)

    total_capacity_mbps = service_rate_bps / 1e6
    per_flow_capacity_mbps = service_rate_bps / args.n_flows / 1e6

    write_timeseries_csv(compare_dir / "timeseries_throughput_aggregate_mbps.csv", grid, aggregate_tput)
    write_timeseries_csv(compare_dir / "timeseries_throughput_mean_per_flow_mbps.csv", grid, mean_tput)
    write_timeseries_csv(compare_dir / "timeseries_queue_delay_mean_ms.csv", grid, mean_qdelay)

    with (compare_dir / "summary_metrics.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "cc",
            "avg_aggregate_throughput_mbps_after_warmup",
            "avg_queue_delay_ms_after_warmup",
            "p95_queue_delay_ms_after_warmup",
            "goodput_trace_files",
            "queue_trace_files",
        ])
        for cc in ccs:
            writer.writerow([
                cc,
                f"{avg_aggregate_tput[cc]:.6f}",
                f"{avg_qdelay[cc]:.6f}",
                f"{p95_qdelay[cc]:.6f}",
                len(raw[cc]["goodput_files"]),  # type: ignore[arg-type]
                len(raw[cc]["queue_files"]),  # type: ignore[arg-type]
            ])

    plot_lines(
        compare_dir / "throughput_aggregate_mbps.png",
        grid,
        aggregate_tput,
        "Aggregate throughput (Mbps)",
        "Aggregate throughput over time",
        total_capacity_mbps,
    )
    plot_lines(
        compare_dir / "throughput_mean_per_flow_mbps.png",
        grid,
        mean_tput,
        "Mean per-flow throughput (Mbps)",
        "Mean per-flow throughput over time",
        per_flow_capacity_mbps,
    )
    plot_lines(
        compare_dir / "queue_delay_mean_ms.png",
        grid,
        mean_qdelay,
        "Mean queueing delay (ms)",
        "Mean switch egress queueing delay over time",
    )
    plot_bar(
        compare_dir / "queue_delay_p95_ms.png",
        p95_qdelay,
        "P95 queueing delay (ms)",
        f"P95 queueing delay after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "throughput_average_mbps.png",
        avg_aggregate_tput,
        "Average aggregate throughput (Mbps)",
        f"Average aggregate throughput after {args.warmup_s:g}s warmup",
    )

    print(f"对比图和汇总 CSV 已写入：{compare_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
