#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plot a multi-CC comparison generated by run_4cc_comparison.py.

Input directory layout:
  experiment_root/
    BBRv2/
    oBBR/
    BBRv2plus/
    FBBR/
    compare/
"""

import argparse
import csv
import math
import re
from bisect import bisect_right
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


DEFAULT_CCS = ("BBRv2", "oBBR", "BBRv2plus", "FBBR")
PLOT_COLORS = {
    "BBRv2": "#1f77b4",
    "oBBR": "#2ca02c",
    "BBRv2plus": "#d62728",
    "FBBR": "#ff7f0e",
    "FBBR-adaptive": "#17becf",
    "FBBR-hybrid": "#e377c2",
    "FBBR-hybridv3": "#bcbd22",
    "FBBR-hybirdv4": "#00a087",
    "FreqCCv3": "#9467bd",
    "BBR-R": "#8c564b",
    "CUBIC": "#7f7f7f",
}


def split_csv(text: str) -> List[str]:
    return [part.strip() for part in str(text).split(",") if part.strip()]


def expand_float_list(text: str, count: int, default: float, name: str) -> List[float]:
    values = [float(part) for part in split_csv(text)] if text else [default]
    if len(values) == 1:
        return values * count
    if len(values) != count:
        raise ValueError(f"{name} 必须给 1 个值或 {count} 个值。")
    return values


def parse_rate_bps(text: str) -> float:
    value = str(text).strip()
    match = re.fullmatch(r"([0-9]+(?:\.[0-9]+)?)\s*([kKmMgG]?)\s*(?:b(?:it)?s?|bps)?", value)
    if not match:
        raise ValueError(f"无法解析速率: {text}")
    number = float(match.group(1))
    unit = match.group(2).lower()
    scale = {"": 1.0, "k": 1e3, "m": 1e6, "g": 1e9}[unit]
    return number * scale


def read_two_column_trace(path: Path) -> List[Tuple[float, float]]:
    rows: List[Tuple[float, float]] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) < 2:
                continue
            try:
                rows.append((float(fields[0]), float(fields[1])))
            except ValueError:
                continue
    rows.sort(key=lambda item: item[0])
    return rows


def read_queue_trace(path: Path, service_rate_bps: float) -> List[Tuple[float, float]]:
    rows: List[Tuple[float, float]] = []
    if path.name == "bottleneck_queue.csv":
        with path.open("r", newline="", encoding="utf-8", errors="replace") as fh:
            for item in csv.DictReader(fh):
                try:
                    time_s = float(item["time_s"])
                    queue_bytes = float(item["queue_bytes"])
                except (KeyError, TypeError, ValueError):
                    continue
                try:
                    capacity_bps = float(item.get("capacity_bps") or service_rate_bps)
                except (TypeError, ValueError):
                    capacity_bps = service_rate_bps
                delay_ms = queue_bytes * 8.0 / max(capacity_bps, 1.0) * 1000.0
                rows.append((time_s, delay_ms))
        rows.sort(key=lambda item: item[0])
        return rows

    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) < 2:
                continue
            try:
                time_s = float(fields[0])
                queue_bytes = float(fields[1])
            except ValueError:
                continue
            delay_ms = queue_bytes * 8.0 / service_rate_bps * 1000.0
            rows.append((time_s, delay_ms))
    rows.sort(key=lambda item: item[0])
    return rows


def read_capacity_trace(path: Path) -> List[Tuple[float, float]]:
    if path.name != "bottleneck_queue.csv":
        return []
    rows: List[Tuple[float, float]] = []
    with path.open("r", newline="", encoding="utf-8", errors="replace") as fh:
        for item in csv.DictReader(fh):
            try:
                time_s = float(item["time_s"])
                capacity_bps = float(item["capacity_bps"])
            except (KeyError, TypeError, ValueError):
                continue
            rows.append((time_s, capacity_bps / 1e6))
    rows.sort(key=lambda item: item[0])
    return rows


def sample_previous(series: Sequence[Tuple[float, float]], grid: Sequence[float]) -> List[float]:
    if not series:
        return [math.nan for _ in grid]
    times = [item[0] for item in series]
    values = [item[1] for item in series]
    sampled: List[float] = []
    for t in grid:
        idx = bisect_right(times, t) - 1
        if idx < 0:
            sampled.append(0.0)
        else:
            sampled.append(values[idx])
    return sampled


def mean_ignore_nan(values: Iterable[float]) -> float:
    valid = [value for value in values if not math.isnan(value)]
    if not valid:
        return math.nan
    return sum(valid) / len(valid)


def percentile(values: Iterable[float], pct: float) -> float:
    valid = sorted(value for value in values if not math.isnan(value))
    if not valid:
        return math.nan
    if len(valid) == 1:
        return valid[0]
    pos = (len(valid) - 1) * pct / 100.0
    lo = int(math.floor(pos))
    hi = int(math.ceil(pos))
    if lo == hi:
        return valid[lo]
    return valid[lo] + (valid[hi] - valid[lo]) * (pos - lo)


def build_time_grid(max_time_s: float, step_s: float) -> List[float]:
    if max_time_s <= 0:
        return [0.0]
    count = int(math.ceil(max_time_s / step_s)) + 1
    return [round(i * step_s, 10) for i in range(count)]


def find_goodput_files(run_dir: Path, trace_name: str, cc: str) -> List[Path]:
    def flow_sort_key(path: Path) -> Tuple[int, str]:
        match = re.search(r"_flow(\d+)_", path.name)
        return (int(match.group(1)) if match else 10**9, path.name)

    exact = sorted(
        run_dir.glob(f"{trace_name}_flow*_{cc}_good.txt"),
        key=flow_sort_key,
    )
    if exact:
        return exact
    return sorted(run_dir.glob("*_flow*_*_good.txt"), key=flow_sort_key)


def find_flow_metric_files(
    run_dir: Path, trace_name: str, cc: str, suffix: str
) -> List[Path]:
    def flow_sort_key(path: Path) -> Tuple[int, str]:
        match = re.search(r"_flow(\d+)_", path.name)
        return (int(match.group(1)) if match else 10**9, path.name)

    exact = sorted(
        run_dir.glob(f"{trace_name}_flow*_{cc}_{suffix}.txt"),
        key=flow_sort_key,
    )
    if exact:
        return exact
    return sorted(
        (
            path
            for path in run_dir.glob(f"*_flow*_*_{suffix}.txt")
            if "_all_stats" not in path.name
        ),
        key=flow_sort_key,
    )


def read_numeric_column_trace(
    path: Path, value_column: int
) -> List[Tuple[float, float]]:
    rows: List[Tuple[float, float]] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) <= value_column:
                continue
            try:
                rows.append((float(fields[0]), float(fields[value_column])))
            except ValueError:
                continue
    rows.sort(key=lambda item: item[0])
    return rows


def read_flow_stats(path: Path) -> Dict[str, float]:
    values: List[float] = []
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                values.append(float(re.split(r"\s+", line)[0]))
            except (IndexError, ValueError):
                continue
    if len(values) < 4:
        return {}
    return {
        "loss_rate_pct": values[0],
        "avg_throughput_kbps": values[1],
        "avg_owd_ms": values[2],
        "total_recv_bytes": values[3],
    }


def read_all_stats(run_dir: Path, trace_name: str) -> Dict[str, float]:
    path = run_dir / f"{trace_name}_all_stats.txt"
    if not path.exists():
        candidates = sorted(run_dir.glob("*_all_stats.txt"))
        if not candidates:
            return {}
        path = candidates[0]
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            fields = re.split(r"\s+", line)
            if len(fields) < 4:
                continue
            try:
                return {
                    "loss_rate_pct": float(fields[1]),
                    "aggregate_throughput_bps": float(fields[2]),
                    "avg_owd_ms": float(fields[3]),
                }
            except ValueError:
                continue
    return {}


def find_queue_files(run_dir: Path, trace_name: str) -> List[Path]:
    fixed_interval = run_dir / "bottleneck_queue.csv"
    if fixed_interval.exists():
        return [fixed_interval]
    shared = sorted(run_dir.glob(f"{trace_name}_shared_bottleneck_queue.txt"))
    if shared:
        return shared
    exact = sorted(run_dir.glob(f"{trace_name}_switch_egress_flow*_bottleneck_queue.txt"))
    if exact:
        return exact
    shared_fallback = sorted(run_dir.glob("*_shared_bottleneck_queue.txt"))
    if shared_fallback:
        return shared_fallback
    return sorted(run_dir.glob("*_switch_egress_flow*_bottleneck_queue.txt"))


def load_cc_data(
    run_dir: Path,
    cc: str,
    trace_name: str,
    service_rate_bps: float,
) -> Dict[str, object]:
    goodput_files = find_goodput_files(run_dir, trace_name, cc)
    queue_files = find_queue_files(run_dir, trace_name)
    loss_files = find_flow_metric_files(run_dir, trace_name, cc, "lossrate")
    flow_stats_files = find_flow_metric_files(run_dir, trace_name, cc, "stats")

    goodput = [read_two_column_trace(path) for path in goodput_files]
    queue_delay = [read_queue_trace(path, service_rate_bps) for path in queue_files]
    cumulative_loss_rate = [
        read_numeric_column_trace(path, 2) for path in loss_files
    ]
    flow_stats = [read_flow_stats(path) for path in flow_stats_files]
    all_stats = read_all_stats(run_dir, trace_name)
    capacity = []
    for path in queue_files:
        capacity = read_capacity_trace(path)
        if capacity:
            break
    max_time = 0.0
    for series in goodput + queue_delay + cumulative_loss_rate + (
        [capacity] if capacity else []
    ):
        if series:
            max_time = max(max_time, series[-1][0])
    return {
        "run_dir": run_dir,
        "goodput_files": goodput_files,
        "queue_files": queue_files,
        "loss_files": loss_files,
        "flow_stats_files": flow_stats_files,
        "goodput": goodput,
        "queue_delay": queue_delay,
        "cumulative_loss_rate": cumulative_loss_rate,
        "flow_stats": flow_stats,
        "all_stats": all_stats,
        "capacity": capacity,
        "max_time": max_time,
    }


def write_timeseries_csv(path: Path, grid: Sequence[float], values_by_cc: Dict[str, Sequence[float]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["time_s", *values_by_cc.keys()])
        for idx, time_s in enumerate(grid):
            row = [time_s]
            for values in values_by_cc.values():
                value = values[idx]
                row.append("" if math.isnan(value) else f"{value:.6f}")
            writer.writerow(row)


def plot_lines(
    output: Path,
    grid: Sequence[float],
    values_by_cc: Dict[str, Sequence[float]],
    ylabel: str,
    title: str,
    ideal_line: Optional[float] = None,
    ideal_values: Optional[Sequence[float]] = None,
    ideal_values_label: str = "ideal fair share",
    transition_times: Sequence[float] = (),
) -> None:
    fig, ax = plt.subplots(figsize=(10.5, 5.6))
    for cc, values in values_by_cc.items():
        ax.plot(grid, values, label=cc, linewidth=1.8, color=PLOT_COLORS.get(cc))
    if ideal_line is not None:
        ax.axhline(ideal_line, color="#555555", linestyle="--", linewidth=1.0, label="ideal capacity")
    if ideal_values is not None:
        ax.plot(
            grid,
            ideal_values,
            color="#555555",
            linestyle="--",
            linewidth=1.0,
            label=ideal_values_label,
        )
    for time_s in transition_times:
        ax.axvline(time_s, color="#777777", linestyle=":", linewidth=1.0)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=2, frameon=False)
    fig.tight_layout()
    fig.savefig(output, dpi=180)
    plt.close(fig)


def plot_bar(
    output: Path,
    values: Dict[str, float],
    ylabel: str,
    title: str,
    yscale: str = "linear",
) -> None:
    fig, ax = plt.subplots(figsize=(10.5, 5.2))
    ccs = list(values.keys())
    heights = [values[cc] for cc in ccs]
    ax.bar(ccs, heights, color=[PLOT_COLORS.get(cc, "#777777") for cc in ccs])
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    if yscale == "symlog":
        ax.set_yscale("symlog", linthresh=0.001)
    elif yscale != "linear":
        ax.set_yscale(yscale)
    ax.tick_params(axis="x", labelrotation=20)
    ax.grid(True, axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(output, dpi=180)
    plt.close(fig)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="汇总四个 CC 子实验的 goodput/队列 trace，并在 compare 目录画对比图。",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("--experiment-dir", required=True, help="复合实验根目录，里面应包含 BBRv2/oBBR/BBRv2plus/FBBR 子目录。")
    parser.add_argument("--service-rate", default="100Mbps", help="共享瓶颈链路速率，用于把队列字节换算成排队延迟。")
    parser.add_argument("--n-flows", type=int, default=4, help="每个子实验的流数量。默认 4。")
    parser.add_argument("--ccs", default=",".join(DEFAULT_CCS), help="要比较的 CC 子目录名，逗号分隔。")
    parser.add_argument(
        "--cc-dirs",
        default="",
        help=(
            "每个 CC 的原始运行目录，逗号分隔；默认使用 "
            "<experiment-dir>/<cc>。可用于汇总分散但配置一致的历史实验。"
        ),
    )
    parser.add_argument("--trace-names", default="", help="每个 CC 对应的 traceName，默认与 CC 名相同。")
    parser.add_argument("--sample-step-s", type=float, default=0.1, help="绘图重采样时间步长。默认 0.1s。")
    parser.add_argument("--warmup-s", type=float, default=5.0, help="汇总平均值时跳过的启动阶段。默认 5s。")
    parser.add_argument("--flow-start-times", default="0", help="每流启动时刻，用于动态流统计。")
    parser.add_argument("--flow-stop-times", default="", help="每流停止时刻，用于动态流统计。")
    parser.add_argument("--sim-time", type=float, default=0.0, help="仿真结束时刻；0 表示从 trace 推断。")
    args = parser.parse_args(argv)

    experiment_dir = Path(args.experiment_dir).expanduser().resolve()
    compare_dir = experiment_dir / "compare"
    compare_dir.mkdir(parents=True, exist_ok=True)

    ccs = split_csv(args.ccs)
    trace_names = split_csv(args.trace_names) if args.trace_names else list(ccs)
    if len(trace_names) != len(ccs):
        raise SystemExit("trace-names 必须为空，或与 ccs 数量相同。")
    trace_name_by_cc = dict(zip(ccs, trace_names))
    if args.cc_dirs:
        cc_dir_tokens = split_csv(args.cc_dirs)
        if len(cc_dir_tokens) != len(ccs):
            raise SystemExit("cc-dirs 必须为空，或与 ccs 数量相同。")
        run_dir_by_cc = {
            cc: Path(path).expanduser().resolve()
            for cc, path in zip(ccs, cc_dir_tokens)
        }
    else:
        run_dir_by_cc = {cc: experiment_dir / cc for cc in ccs}
    missing_dirs = [cc for cc, path in run_dir_by_cc.items() if not path.is_dir()]
    if missing_dirs:
        raise SystemExit(f"缺少 CC 运行目录：{', '.join(missing_dirs)}")
    service_rate_bps = parse_rate_bps(args.service_rate)
    flow_start_times = expand_float_list(
        args.flow_start_times, args.n_flows, 0.0, "flow-start-times"
    )

    raw = {
        cc: load_cc_data(
            run_dir_by_cc[cc], cc, trace_name_by_cc[cc], service_rate_bps
        )
        for cc in ccs
    }
    max_time = max(float(item["max_time"]) for item in raw.values())
    sim_end_s = args.sim_time if args.sim_time > 0.0 else max_time
    flow_stop_times = expand_float_list(
        args.flow_stop_times, args.n_flows, sim_end_s, "flow-stop-times"
    )
    grid = build_time_grid(max_time, args.sample_step_s)

    def active_indexes(time_s: float) -> List[int]:
        return [
            idx
            for idx in range(args.n_flows)
            if flow_start_times[idx] <= time_s < flow_stop_times[idx]
        ]

    active_counts = [len(active_indexes(time_s)) for time_s in grid]
    capacity_series: List[Tuple[float, float]] = []
    for cc in ccs:
        candidate = raw[cc].get("capacity", [])  # type: ignore[union-attr]
        if candidate:
            capacity_series = candidate  # type: ignore[assignment]
            break
    capacity_mbps = (
        sample_previous(capacity_series, grid)
        if capacity_series
        else [service_rate_bps / 1e6 for _ in grid]
    )

    aggregate_tput: Dict[str, List[float]] = {}
    mean_tput: Dict[str, List[float]] = {}
    mean_qdelay: Dict[str, List[float]] = {}
    cumulative_loss_rate: Dict[str, List[float]] = {}
    p95_qdelay: Dict[str, float] = {}
    avg_qdelay: Dict[str, float] = {}
    avg_aggregate_tput: Dict[str, float] = {}
    avg_mean_tput: Dict[str, float] = {}
    avg_capacity_mbps: Dict[str, float] = {}
    avg_utilization: Dict[str, float] = {}
    avg_instantaneous_utilization: Dict[str, float] = {}
    avg_jain_fairness: Dict[str, float] = {}
    aggregate_loss_rate: Dict[str, float] = {}
    avg_owd: Dict[str, float] = {}
    total_received_bytes: Dict[str, float] = {}
    jain_fairness: Dict[str, List[float]] = {}

    for cc in ccs:
        goodput_series = raw[cc]["goodput"]  # type: ignore[index]
        queue_series = raw[cc]["queue_delay"]  # type: ignore[index]
        loss_series = raw[cc]["cumulative_loss_rate"]  # type: ignore[index]
        sampled_goodput = [sample_previous(series, grid) for series in goodput_series]  # type: ignore[arg-type]
        sampled_queue = [sample_previous(series, grid) for series in queue_series]  # type: ignore[arg-type]
        sampled_loss = [sample_previous(series, grid) for series in loss_series]  # type: ignore[arg-type]

        for flow_idx, values in enumerate(sampled_goodput):
            if flow_idx >= args.n_flows:
                break
            for grid_idx, time_s in enumerate(grid):
                if not (
                    flow_start_times[flow_idx]
                    <= time_s
                    < flow_stop_times[flow_idx]
                ):
                    values[grid_idx] = 0.0

        aggregate: List[float] = []
        per_flow_mean: List[float] = []
        fairness: List[float] = []
        for idx in range(len(grid)):
            values_kbps = [series[idx] for series in sampled_goodput]
            total_mbps = sum(v for v in values_kbps if not math.isnan(v)) / 1000.0
            aggregate.append(total_mbps)
            active = active_indexes(grid[idx])
            active_values = [
                values_kbps[flow_idx]
                for flow_idx in active
                if flow_idx < len(values_kbps) and not math.isnan(values_kbps[flow_idx])
            ]
            per_flow_mean.append(
                mean_ignore_nan(active_values) / 1000.0 if active_values else 0.0
            )
            denominator = len(active_values) * sum(value * value for value in active_values)
            fairness.append(
                (sum(active_values) ** 2 / denominator)
                if denominator > 0.0
                else math.nan
            )
        aggregate_tput[cc] = aggregate
        mean_tput[cc] = per_flow_mean
        jain_fairness[cc] = fairness

        q_mean: List[float] = []
        for idx in range(len(grid)):
            q_mean.append(mean_ignore_nan(series[idx] for series in sampled_queue))
        mean_qdelay[cc] = q_mean
        cumulative_loss_rate[cc] = [
            mean_ignore_nan(series[idx] for series in sampled_loss)
            for idx in range(len(grid))
        ]

        steady_indexes = [
            idx
            for idx, time_s in enumerate(grid)
            if args.warmup_s <= time_s < sim_end_s
        ]
        if not steady_indexes:
            steady_indexes = list(range(len(grid)))
        steady_tput = [aggregate[idx] for idx in steady_indexes]
        steady_q = [q_mean[idx] for idx in steady_indexes]
        avg_aggregate_tput[cc] = mean_ignore_nan(steady_tput)
        avg_mean_tput[cc] = mean_ignore_nan(
            per_flow_mean[idx] for idx in steady_indexes
        )
        avg_capacity_mbps[cc] = mean_ignore_nan(
            capacity_mbps[idx] for idx in steady_indexes
        )
        # For a rapidly changing cellular trace, mean(throughput/capacity) can
        # exceed one when queued data is delivered just after a capacity drop.
        # Ratio-of-means is the meaningful whole-window utilization; retain the
        # mean instantaneous ratio separately as a diagnostic.
        avg_utilization[cc] = (
            avg_aggregate_tput[cc] / avg_capacity_mbps[cc]
            if avg_capacity_mbps[cc] > 0.0
            else math.nan
        )
        avg_instantaneous_utilization[cc] = mean_ignore_nan(
            aggregate[idx] / capacity_mbps[idx]
            for idx in steady_indexes
            if capacity_mbps[idx] > 0.0
        )
        avg_qdelay[cc] = mean_ignore_nan(steady_q)
        p95_qdelay[cc] = percentile(steady_q, 95.0)
        avg_jain_fairness[cc] = mean_ignore_nan(
            fairness[idx] for idx in steady_indexes
        )
        all_stats = raw[cc]["all_stats"]  # type: ignore[index]
        flow_stats = raw[cc]["flow_stats"]  # type: ignore[index]
        aggregate_loss_rate[cc] = float(
            all_stats.get(  # type: ignore[union-attr]
                "loss_rate_pct",
                mean_ignore_nan(
                    item.get("loss_rate_pct", math.nan)  # type: ignore[union-attr]
                    for item in flow_stats  # type: ignore[union-attr]
                ),
            )
        )
        avg_owd[cc] = float(
            all_stats.get(  # type: ignore[union-attr]
                "avg_owd_ms",
                mean_ignore_nan(
                    item.get("avg_owd_ms", math.nan)  # type: ignore[union-attr]
                    for item in flow_stats  # type: ignore[union-attr]
                ),
            )
        )
        total_received_bytes[cc] = sum(
            item.get("total_recv_bytes", 0.0)  # type: ignore[union-attr]
            for item in flow_stats  # type: ignore[union-attr]
        )

    total_capacity_mbps = service_rate_bps / 1e6
    ideal_per_flow_mbps = [
        capacity_mbps[idx] / count if count > 0 else 0.0
        for idx, count in enumerate(active_counts)
    ]

    write_timeseries_csv(compare_dir / "timeseries_throughput_aggregate_mbps.csv", grid, aggregate_tput)
    write_timeseries_csv(compare_dir / "timeseries_throughput_mean_per_flow_mbps.csv", grid, mean_tput)
    write_timeseries_csv(compare_dir / "timeseries_queue_delay_mean_ms.csv", grid, mean_qdelay)
    write_timeseries_csv(compare_dir / "timeseries_jain_fairness.csv", grid, jain_fairness)
    write_timeseries_csv(
        compare_dir / "timeseries_cumulative_loss_rate_pct.csv",
        grid,
        cumulative_loss_rate,
    )
    write_timeseries_csv(compare_dir / "timeseries_active_flows.csv", grid, {"active_flows": active_counts})
    write_timeseries_csv(compare_dir / "timeseries_capacity_mbps.csv", grid, {"capacity_mbps": capacity_mbps})

    with (compare_dir / "comparison_sources.csv").open(
        "w", newline="", encoding="utf-8"
    ) as fh:
        writer = csv.writer(fh)
        writer.writerow(
            ["cc", "trace_name", "source_run_dir", "trace_end_time_s"]
        )
        for cc in ccs:
            writer.writerow(
                [
                    cc,
                    trace_name_by_cc[cc],
                    str(run_dir_by_cc[cc]),
                    f"{float(raw[cc]['max_time']):.6f}",
                ]
            )

    with (compare_dir / "per_flow_summary_metrics.csv").open(
        "w", newline="", encoding="utf-8"
    ) as fh:
        writer = csv.writer(fh)
        writer.writerow(
            [
                "cc",
                "flow_index",
                "loss_rate_pct_whole_run",
                "avg_throughput_kbps_whole_run",
                "avg_one_way_delay_ms_whole_run",
                "total_received_bytes",
            ]
        )
        for cc in ccs:
            for flow_index, item in enumerate(raw[cc]["flow_stats"], start=1):  # type: ignore[index]
                writer.writerow(
                    [
                        cc,
                        flow_index,
                        f"{item.get('loss_rate_pct', math.nan):.9f}",  # type: ignore[union-attr]
                        f"{item.get('avg_throughput_kbps', math.nan):.6f}",  # type: ignore[union-attr]
                        f"{item.get('avg_owd_ms', math.nan):.6f}",  # type: ignore[union-attr]
                        f"{item.get('total_recv_bytes', math.nan):.0f}",  # type: ignore[union-attr]
                    ]
                )

    with (compare_dir / "summary_metrics.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "cc",
            "avg_aggregate_throughput_mbps_after_warmup",
            "avg_per_flow_throughput_mbps_after_warmup",
            "avg_bottleneck_capacity_mbps_after_warmup",
            "avg_bottleneck_utilization_after_warmup",
            "mean_instantaneous_throughput_capacity_ratio_after_warmup",
            "avg_queue_delay_ms_after_warmup",
            "p95_queue_delay_ms_after_warmup",
            "avg_jain_fairness_after_warmup",
            "aggregate_loss_rate_pct_whole_run",
            "avg_one_way_delay_ms_whole_run",
            "total_received_bytes_whole_run",
            "goodput_trace_files",
            "queue_trace_files",
            "loss_trace_files",
            "source_run_dir",
        ])
        for cc in ccs:
            writer.writerow([
                cc,
                f"{avg_aggregate_tput[cc]:.6f}",
                f"{avg_mean_tput[cc]:.6f}",
                f"{avg_capacity_mbps[cc]:.6f}",
                f"{avg_utilization[cc]:.6f}",
                f"{avg_instantaneous_utilization[cc]:.6f}",
                f"{avg_qdelay[cc]:.6f}",
                f"{p95_qdelay[cc]:.6f}",
                f"{avg_jain_fairness[cc]:.6f}",
                f"{aggregate_loss_rate[cc]:.9f}",
                f"{avg_owd[cc]:.6f}",
                f"{total_received_bytes[cc]:.0f}",
                len(raw[cc]["goodput_files"]),  # type: ignore[arg-type]
                len(raw[cc]["queue_files"]),  # type: ignore[arg-type]
                len(raw[cc]["loss_files"]),  # type: ignore[arg-type]
                str(run_dir_by_cc[cc]),
            ])

    phase_boundaries = sorted(
        {
            0.0,
            sim_end_s,
            *(
                value
                for value in [*flow_start_times, *flow_stop_times]
                if 0.0 < value < sim_end_s
            ),
        }
    )
    with (compare_dir / "phase_summary_metrics.csv").open(
        "w", newline="", encoding="utf-8"
    ) as fh:
        writer = csv.writer(fh)
        writer.writerow([
            "cc",
            "phase_index",
            "phase_start_s",
            "metric_start_s",
            "phase_end_s",
            "active_flows",
            "avg_aggregate_throughput_mbps",
            "avg_bottleneck_utilization",
            "avg_active_flow_throughput_mbps",
            "avg_queue_delay_ms",
            "p95_queue_delay_ms",
            "avg_jain_fairness",
        ])
        for cc in ccs:
            for phase_index, (phase_start, phase_end) in enumerate(
                zip(phase_boundaries, phase_boundaries[1:]), start=1
            ):
                metric_start = min(phase_end, phase_start + args.warmup_s)
                indexes = [
                    idx
                    for idx, time_s in enumerate(grid)
                    if metric_start <= time_s < phase_end
                ]
                if not indexes:
                    indexes = [
                        idx
                        for idx, time_s in enumerate(grid)
                        if phase_start <= time_s < phase_end
                    ]
                active = len(active_indexes((phase_start + phase_end) / 2.0))
                avg_tput = mean_ignore_nan(aggregate_tput[cc][idx] for idx in indexes)
                avg_per_flow = mean_ignore_nan(mean_tput[cc][idx] for idx in indexes)
                avg_queue = mean_ignore_nan(mean_qdelay[cc][idx] for idx in indexes)
                p95_queue = percentile((mean_qdelay[cc][idx] for idx in indexes), 95.0)
                avg_fairness = mean_ignore_nan(jain_fairness[cc][idx] for idx in indexes)
                avg_capacity = mean_ignore_nan(capacity_mbps[idx] for idx in indexes)
                writer.writerow([
                    cc,
                    phase_index,
                    f"{phase_start:.6f}",
                    f"{metric_start:.6f}",
                    f"{phase_end:.6f}",
                    active,
                    f"{avg_tput:.6f}",
                    f"{avg_tput / avg_capacity:.6f}" if avg_capacity > 0.0 else "",
                    f"{avg_per_flow:.6f}",
                    f"{avg_queue:.6f}",
                    f"{p95_queue:.6f}",
                    f"{avg_fairness:.6f}",
                ])

    plot_lines(
        compare_dir / "throughput_aggregate_mbps.png",
        grid,
        aggregate_tput,
        "Aggregate throughput (Mbps)",
        "Aggregate throughput over time",
        None if capacity_series else total_capacity_mbps,
        ideal_values=capacity_mbps if capacity_series else None,
        ideal_values_label="ideal capacity",
        transition_times=phase_boundaries[1:-1],
    )
    plot_lines(
        compare_dir / "throughput_mean_per_flow_mbps.png",
        grid,
        mean_tput,
        "Mean per-flow throughput (Mbps)",
        "Mean per-flow throughput over time",
        ideal_values=ideal_per_flow_mbps,
        ideal_values_label="ideal fair share",
        transition_times=phase_boundaries[1:-1],
    )
    plot_lines(
        compare_dir / "queue_delay_mean_ms.png",
        grid,
        mean_qdelay,
        "Mean queueing delay (ms)",
        "Mean switch egress queueing delay over time",
        transition_times=phase_boundaries[1:-1],
    )
    plot_lines(
        compare_dir / "jain_fairness_over_time.png",
        grid,
        jain_fairness,
        "Jain fairness index",
        "Jain fairness over time",
        transition_times=phase_boundaries[1:-1],
    )
    plot_lines(
        compare_dir / "loss_rate_cumulative_pct.png",
        grid,
        cumulative_loss_rate,
        "Mean cumulative loss rate (%)",
        "Mean cumulative packet loss rate over time",
        transition_times=phase_boundaries[1:-1],
    )
    plot_lines(
        compare_dir / "active_flows.png",
        grid,
        {"active flows": active_counts},
        "Active flows",
        "Active flow count over time",
        transition_times=phase_boundaries[1:-1],
    )
    plot_bar(
        compare_dir / "queue_delay_p95_ms.png",
        p95_qdelay,
        "P95 queueing delay (ms)",
        f"P95 queueing delay after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "queue_delay_average_ms.png",
        avg_qdelay,
        "Average queueing delay (ms)",
        f"Average queueing delay after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "throughput_average_mbps.png",
        avg_aggregate_tput,
        "Average aggregate throughput (Mbps)",
        f"Average aggregate throughput after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "jain_fairness_average.png",
        avg_jain_fairness,
        "Average Jain fairness index",
        f"Average Jain fairness after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "bottleneck_utilization_average.png",
        avg_utilization,
        "Average bottleneck utilization",
        f"Average bottleneck utilization after {args.warmup_s:g}s warmup",
    )
    plot_bar(
        compare_dir / "loss_rate_average_pct.png",
        aggregate_loss_rate,
        "Aggregate packet loss rate (%)",
        "Aggregate packet loss rate over the whole run",
        yscale="symlog",
    )
    plot_bar(
        compare_dir / "one_way_delay_average_ms.png",
        avg_owd,
        "Average one-way delay (ms)",
        "Average one-way delay over the whole run",
    )
    plot_bar(
        compare_dir / "total_received_gib.png",
        {
            cc: total_received_bytes[cc] / (1024.0 ** 3)
            for cc in ccs
        },
        "Total received data (GiB)",
        "Total data received by all flows",
    )

    print(f"对比图和汇总 CSV 已写入：{compare_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
