## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program(
        'test1-probe-order',
        ['core', 'network', 'internet', 'point-to-point', 'applications',
         'traffic-control', 'dqc'])
    obj.source = 'test1-probe-order.cc'
