## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program(
        'test3-dynamic-rtt',
        ['core', 'network', 'internet', 'point-to-point', 'applications',
         'traffic-control', 'dqc'])
    obj.source = 'test3-dynamic-rtt.cc'
